name: PATH testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Check PATH and env
      run: |
        echo $PATH
        env
        
    - name: Check PATH and env
      run: |
        echo 'hello 0'
        which bash
        /bin/bash
        echo 'hello 1'
        exit
        /usr/bin/env bash
        echo 'hello 2'
        exit
